name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hello @${{ github.actor }}! 

            Thank you for raising an issue 🚀. We truly value your effort in helping us improve **DevNation CMS**. Our team will review it promptly. In the meantime, please ensure you have checked the existing issues to avoid duplicates.

            If this is for **Hacktoberfest 2024**, don't forget to label your issue as `hacktoberfest-accepted`. Stay tuned and happy coding! 💻
          pr-message: |
            🎉 Hey @${{ github.actor }}!

            Thank you for your contribution 🎊. Your pull request has been submitted successfully! A maintainer will review it as soon as possible. 

            We appreciate your support in making **DevNation CMS** better. If this is part of **Hacktoberfest 2024**, please ensure your PR aligns with our contribution guidelines. 

            Let's build something amazing together 🚀. Happy contributing! 🌟
